"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""


a = 2
b = 3
i = 0
sum =  2
while i < 4000000:
    i = a + b
    a = b
    b = i
    if i % 2 == 0:
        sum += i
print(sum)

# Checking "002.py" against solution: 4613732
# Time elapsed: user: 10.5 ms, sys: 7.44 ms, total: 17.9 ms
